### ISSUE TITLE
How much GPU memory do you have?

### ISSUE THREAD

**Issue by wowwowya** [c-yn/FocalNet#3]
How much GPU memory do you have? I'm training a model on reside-indoor, and it's showing 'CUDA out of memory' error. My graphics card is 4060 with 8GB.

**Comment by wowwowya** [comment]
it shows torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 256.00 MiB (GPU 0; 8.00 GiB total capacity; 933.87 MiB already allocated; 4.95 GiB free; 948.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by c-yn** [comment]
Hi, training ITS needs about 17G memory.

**Comment by wowwowya** [comment]
How many epochs are needed in total for training on ITS?thankyou

**Comment by c-yn** [comment]
Hi, the hyper-parameters we used are shown in the main.py.
