### ISSUE TITLE
about FSM

### ISSUE THREAD

**Issue by kkllww** [c-yn/FocalNet#6]
What is the code for FSM and the specific process for obtaining high frequencies

**Comment by c-yn** [comment]
Hi, 
FSM is implemented by class LocalAttention. 
We obtain the high frequencies by subtracting the lowest frequency from the input features.

**Comment by kkllww** [comment]
May I ask which specific code in FocalNet.py you have published to obtain high frequencies? Please indicate the specific number of lines. I did not find the relevant code for subtracting the lowest frequency from the input features

**Comment by c-yn** [comment]
Hi, Line 57 in FocalNet.py.
